### ISSUE TITLE
Issue about installation

### ISSUE THREAD

**Issue by hilarych** [wulwife/LOKI#2]
Hi Francesco,
Do I need to install the package or I can just import them in my code?
Is there a manual or example code that can help me get started and test it?
Would you tell me what type of data should I put in the directory "db_path"(in the code)?

Thank you very much!
Hilary

**Comment by wulwife** [comment]
Hi Hillary sorry for the very late response, I have just realised now about the existence of this message.
This version of the code it is under development. I can send you and alpha version of the code if you need to use it.
Regards
Francesco

**Comment by wulwife** [comment]
I have added a test dataset. You have to compile the c files in the src_c folder and using installation.py.
Then to test if everything works try to launch the file test.py. I am still working on the code and it cannot be considered yet the final version.

**Comment by hilarych** [comment]
Dear Dr. Grigoli,

Thank you very much!

I have written my code referencing your paper Grigoli et al. (2013). But the original LOKI code would be very helpful!

 

Best,

HILARY CHANG  |   UNDERGRADUATE STUDENT

Department of Earth Sciences
Memorial University of Newfoundland
St. John’s, Newfoundland
T  709 351 6039

 <mailto:hilaryc@mun.ca> hilaryc@mun.ca


www.mun.ca
