### ISSUE TITLE
Missing file piton_topo

### ISSUE THREAD

**Issue by apointing** [wulwife/LOKI#3]
Hi,
Trying to create my own 3D velocity model using 3D_model_gen.py. However there is an example file missing "piton_topo", which appears to be needed. I would like to know the format of this file and how it is used - it looks to define the boundaries of the area?
Thanks, Alan

**Comment by wulwife** [comment]
Hi Alan,
The file Piton_topo is the topography of the volcano Piton de la Fournaise.
I am adding it in a separate folder. The 3D_model_gen is just a quick and dirty script to create 3D velocity models. It is not clean at all and it is not the definitive version, so pay attention there could be bugs.
Francesco

**Comment by apointing** [comment]
Hi Francesco,
Thanks for the feedback, please can you upload the file when you have time, as I can't see it in the separate directory you mentioned. Thinking ahead, if I have a flat topography can I put zeros in the "piton_topo" file.
Thanks again, Kind Regards, Alan
