### ISSUE TITLE
.buf file in tests_data

### ISSUE THREAD

**Issue by himanshu1601** [wulwife/LOKI#8]
Can anyone here assist me with the .time.buf files located in the tests/Test_dataset/Traveltimes folder? This file's kind and whether it was created by code or downloaded.

**Comment by 604148386** [comment]
created using https://github.com/alomax/NonLinLoc

**Comment by wulwife** [comment]
Thanks Antony, I this it is written in the documentation, if not I am going to add it
Cheers
Francesco
